// Copyright 2022 Giuseppe De Palma, Matteo Trentin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	docker "github.com/funlessdev/fl-cli/pkg/docker"

	mock "github.com/stretchr/testify/mock"
)

// DockerRemover is an autogenerated mock type for the DockerRemover type
type DockerRemover struct {
	mock.Mock
}

// RemoveCoreContainer provides a mock function with given fields: ctx
func (_m *DockerRemover) RemoveCoreContainer(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFLNetwork provides a mock function with given fields: ctx
func (_m *DockerRemover) RemoveFLNetwork(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemovePromContainer provides a mock function with given fields: ctx
func (_m *DockerRemover) RemovePromContainer(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWorkerContainer provides a mock function with given fields: ctx
func (_m *DockerRemover) RemoveWorkerContainer(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithDockerClient provides a mock function with given fields: cli
func (_m *DockerRemover) WithDockerClient(cli docker.DockerClient) {
	_m.Called(cli)
}

type mockConstructorTestingTNewDockerRemover interface {
	mock.TestingT
	Cleanup(func())
}

// NewDockerRemover creates a new instance of DockerRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDockerRemover(t mockConstructorTestingTNewDockerRemover) *DockerRemover {
	mock := &DockerRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
