// Copyright 2022 Giuseppe De Palma, Matteo Trentin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	openapi "github.com/funlessdev/fl-client-sdk-go"
	mock "github.com/stretchr/testify/mock"
)

// ModHandler is an autogenerated mock type for the ModHandler type
type ModHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, modName
func (_m *ModHandler) Create(ctx context.Context, modName string) error {
	ret := _m.Called(ctx, modName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, modName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, modName
func (_m *ModHandler) Delete(ctx context.Context, modName string) error {
	ret := _m.Called(ctx, modName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, modName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, modName
func (_m *ModHandler) Get(ctx context.Context, modName string) (openapi.SingleModuleResult, error) {
	ret := _m.Called(ctx, modName)

	var r0 openapi.SingleModuleResult
	if rf, ok := ret.Get(0).(func(context.Context, string) openapi.SingleModuleResult); ok {
		r0 = rf(ctx, modName)
	} else {
		r0 = ret.Get(0).(openapi.SingleModuleResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, modName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *ModHandler) List(ctx context.Context) (openapi.ModuleNamesResult, error) {
	ret := _m.Called(ctx)

	var r0 openapi.ModuleNamesResult
	if rf, ok := ret.Get(0).(func(context.Context) openapi.ModuleNamesResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(openapi.ModuleNamesResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, modName, newName
func (_m *ModHandler) Update(ctx context.Context, modName string, newName string) error {
	ret := _m.Called(ctx, modName, newName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, modName, newName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewModHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewModHandler creates a new instance of ModHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewModHandler(t mockConstructorTestingTNewModHandler) *ModHandler {
	mock := &ModHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
